config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'

  post '/adventures/:id', to: 'battles#create'

  get '/users/:id/party', to: 'characters#index'

  post '/users/:id/characters/new', to: 'characters#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#google'
  get '/auth/failure', to: redirect('/')

  resources :users
  resources :adventures
  resources :battles

  resources :users do
    resources :adventures, only: %i[new create index]
  end

  resources :users do
    resources :characters, only: %i[new create index]
  end
end

app/models/adventure.rb
class Adventure < ApplicationRecord
  belongs_to :user
  has_many :battles
  has_many :characters, through: :battles

  validates_presence_of :title, :flavor
  validates_uniqueness_of :title, :flavor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :character
  belongs_to :adventure


  def level_up
    if adventure.boss_lv >= character.lv
      new_lv = character.lv += 1
      character.update(lv: new_lv)
      'You leveled up!'
    else
      'This adventure is no match for you now! Choose another.'
    end
  end

  def game_over
    character.destroy
    'Game Over'
  end

  def dice_roll
    character.lv + rand(0..5)
  end

  def results
    if character.tribe == 'Clavat'
      dice_roll + bonus >= adventure.clavat_difficulty ? level_up : game_over
    elsif character.tribe == 'Lilty'
      dice_roll + bonus >= adventure.lilty_difficulty ? level_up : game_over
    elsif character.tribe == 'Selkie'
      dice_roll + bonus >= adventure.selkie_difficulty ? level_up : game_over
    else
      character.tribe == 'Yuke'
      dice_roll + bonus >= adventure.yuke_difficulty ? level_up : game_over
    end
  end
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_many :battles, dependent: :destroy
  has_many :adventures, through: :battles



  validates_presence_of :name, :tribe


  scope :party, ->(user) { where('user_id = ?', user.id) }




end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters
  has_many :adventures
  has_many :battles, through: :characters

  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email

  scope :admins, -> { where(admin: true)}

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @adventures = @user.adventures
    else
      @adventures = Adventure.all
    end
  end

  def new
    admin_check
    @adventure = Adventure.new
  end

  def show
    current_adventure
  end

  def create
    @adventure = current_user.adventures.build(adventure_params)
    if @adventure.save
      redirect_to user_path(current_user), notice: 'Adventure created!'
    else
      render 'new', notice: 'Adventure exists. Try another.'
    end
  end

  def edit
    admin_check
    current_adventure
  end

  def update
    current_adventure
    if @adventure.update(adventure_params)
      redirect_to adventure_path(@adventure), notice: 'Update successful!'
    else
      redirect_to edit_adventure_path,
                  notice: 'Title or flavor text exists. Please try another.'
    end
  end

  def destroy
    current_adventure.destroy
    redirect_to root_path, notice: 'Adventure deleted'
  end

  private

  def adventure_params
    params.require(:adventure).permit(
      :title,
      :flavor,
      :boss,
      :boss_lv,
      :clavat_difficulty,
      :lilty_difficulty,
      :selkie_difficulty,
      :yuke_difficulty
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :authentication_check, :admin, :current_adventure, :user_check, :admin_check

  private

  def authentication_check
    redirect_to root_path if !logged_in?
  end

  def logged_in?
    !!session[:user_id]
  end

  def admin
    current_user.admin
  end

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def current_adventure
    @adventure ||= Adventure.find_by(id: params[:id])
  end

  def user_check
    redirect_to root_path, notice: "User doesn't match or exist." unless params[:user_id] && current_user = User.find_by_id(params[:user_id])
  end

  def admin_check
    redirect_to root_path, notice: 'Must be admin.' unless admin
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def create
    @battle = current_adventure.battles.build(battle_params)
    @battle.character_id = current_user.characters.first.id


    redirect_to root_path, notice: @battle.results
  end

  private

  def battle_params
    params.require(:battle).permit(:bonus)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    if current_user
      @characters = Character.party(current_user)
    else
      render 'new'
    end
  end

  def new
    party_limit
    user_check
    @character = current_user.characters.build
  end

  def create
    @character = current_user.characters.build(character_params)
    if @character.save
      redirect_to adventures_path, notice: "You're ready for an Adventure!"
    else
      render 'new', notice: 'Sorry, one character at a time.'
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :tribe, :lv)
  end

    def party_limit
    if !current_user.characters.empty?
      redirect_to adventures_path, notice: "Party limit reached. You're ready for an adventure!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def home
    redirect_to user_characters_path(current_user) if logged_in?
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.save && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_characters_path(@user), notice: 'Welcome back!'
    else
      redirect_to root_path, notice: 'Invalid login. It happens.'
    end
  end

  def google
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authentication_check, only: %i[show]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Create a character to begin.'
    else
      render 'new'
    end
  end

  def show
    current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper; end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end
end

app/helpers/battle_helper.rb
module BattleHelper; end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper; end

app/helpers/users_helper.rb
module UsersHelper; end

app/views/adventures/edit.html.erb
<h1> Edit Adventure </h1>



<%= form_for(@adventure) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, required: true %>
<br>
<br>
    <%= f.label :flavor %>
    <%= f.text_area :flavor, required: true, size: "50x10" %>
<br>
<br>
    <%= f.label :boss %>
    <%= f.text_field :boss, required: true %>
<br>
<br>
    <%= f.label :boss_lv %>
    <%= f.number_field :boss_lv, required: true %>
<br>
<br>    
    <%= f.label :clavat_difficulty %>
    <%= f.number_field :clavat_difficulty, required: true %>
<br>
<br>    
    <%= f.label :lilty_difficulty %>
    <%= f.number_field :lilty_difficulty, required: true %>
<br>
<br>    
    <%= f.label :selkie_difficulty %>
    <%= f.number_field :selkie_difficulty, required: true %>
<br>
<br>    
    <%= f.label :yuke_difficulty %>
    <%= f.number_field :yuke_difficulty, required: true %>
<br>
<br>    


    <%= f.submit "Submit" %>

<%end%>

app/views/adventures/index.html.erb
<h1> Adventures </h1>
<% @adventures.each do |adv|%>
<p>
<h3><%= link_to adv.title, adventure_path(adv) %></h3>
<b>Boss:</b> <%= adv.boss %>
<br>
<br>
<%= adv.flavor %>

</p>
<%end%>

app/views/adventures/new.html.erb
<h1> New Adventure </h1>

<% flash.each do |type, msg| %>
    <h2>
        <%= msg %>
    </h2>
<% end %>

<%= form_for(@adventure) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, required: true %>
<br>
<br>
    <%= f.label :flavor %>
    <%= f.text_area :flavor, required: true, size: "50x10" %>
<br>
<br>
    <%= f.label :boss %>
    <%= f.text_field :boss, required: true %>
<br>
<br>
    <%= f.label :boss_lv %>
    <%= f.number_field :boss_lv, required: true %>
<br>
<br>    
    <%= f.label :clavat_difficulty %>
    <%= f.number_field :clavat_difficulty, required: true %>
<br>
<br>    
    <%= f.label :lilty_difficulty %>
    <%= f.number_field :lilty_difficulty, required: true %>
<br>
<br>    
    <%= f.label :selkie_difficulty %>
    <%= f.number_field :selkie_difficulty, required: true %>
<br>
<br>    
    <%= f.label :yuke_difficulty %>
    <%= f.number_field :yuke_difficulty, required: true %>
<br>
<br>    


    <%= f.submit "Submit" %>

<%end%>

app/views/adventures/show.html.erb
<h1>Adventure Details</h1>
    <% flash.each do |type, msg| %>
    <h2>
        <%= msg %>
    </h2>
    <% end %>

<% if admin%>
    <%= link_to "Edit Adventure", edit_adventure_path %> |
    <%= link_to "Delete Adventure", adventure_path, :method => :delete %>
<%end%>

<h2><%= current_adventure.title%></h2>

<br>
<br>
<b> Boss name: <%= current_adventure.boss%> </b>
<p>
<%= current_adventure.flavor%>
<br>
<br>
<%= link_to "Adventures by #{current_adventure.user.email}", user_adventures_path(current_adventure.user) %>
</p>
<% if !current_user.characters.empty?%>
<%= form_for :battle do |f| %>
     <p>
        <b>Select your difficulty</b>
        <%= f.radio_button :bonus, 0, required: true %> Normal
        <%= f.radio_button :bonus, 2, required: true %> Easy
    </p>
<br>
<br>
    <%= f.submit "Begin" %>

<% end %>
<% end %>

app/views/characters/index.html.erb
<h1>Party Members</h1>
<br>
    <% flash.each do |type, msg| %>
        <h2>
            <%= msg %>
        </h2>
    <% end %>
<br>
<br>
<div>
    <% @characters.each do |char|%>
        <h2><%= char.name %> the <%= char.tribe %><br> </h2>
        <b>Level <%= char.lv %></b>
    <%end%>
</div>
<h3>Choose an Adventure!</h3>
<%= link_to "All Adventures", adventures_path %>
<h4>By User</h4>
<% User.admins.each do |admin|%>
    <p>
    <%= link_to admin.email, user_adventures_path(admin) %>
    </p>
<% end %>

app/views/characters/new.html.erb
<h1>Welcome to the party!</h1>
<% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

<%= form_for(:character) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
<br>
<br>
<p>
    <b>Tribe</b>
    <%= f.radio_button :tribe, 'Clavat', required: true %> Clavat
    <%= f.radio_button :tribe, 'Lilty', required: true %> Lilty
    <%= f.radio_button :tribe, 'Selkie', required: true %> Selkie
    <%= f.radio_button :tribe, 'Yuke', required: true %> Yuke
</p>
<br>
<br>
    <%= f.submit "Submit" %>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FFCC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if logged_in? %>
      <%= link_to "Log Out", logout_path, method: "delete" %> |
      <%= link_to "Home", root_path %> |
        <% if current_user.characters.empty? %>
        <%= link_to "New Character", new_user_character_path(current_user) %> |
        <%end%>
        <% if admin%>
        <%= link_to "Create Adventure", new_adventure_path %>
        <%end%>
      <%end%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for(@user) do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email, required: true %>
<br>
<br>
    <%= f.label :password %>
    <%= f.password_field :password, required: true %>
<br>
<br>
    <%= f.submit "Submit" %>

<%end%>

app/views/users/show.html.erb
<h1> User Home </h1>